In [4]:
import pandas as pd

Definición de datos

In [7]:
data={'nombre':['Juan','Maria','Pedro','Ana'],
      'edad':[20,25,30,35],
      'ciudad':['Santiago','Valparaiso','Concepcion','Antofagasta']}

In [11]:
df = pd.DataFrame(data)

In [14]:
df.head()

  nombre  edad       ciudad
0   Juan    20     Santiago
1  Maria    25   Valparaiso
2  Pedro    30   Concepcion
3    Ana    35  Antofagasta

Acceder a los datos

In [ ]:
# Acceder a los datos

# Se accede a los datos por medio de los nombres de las columnas, se muestra una serie
# Al menos que se especifique con doble corchete, se muestra un dataframe
print(df['nombre'])
print(df['edad'])

0     Juan
1    Maria
2    Pedro
3      Ana
Name: nombre, dtype: str
0    20
1    25
2    30
3    35
Name: edad, dtype: int64

Empleando iloc (posición) - No se puede modificar

In [21]:
df.iloc[0]

nombre        Juan
edad            20
ciudad    Santiago
Name: 0, dtype: object

In [22]:
df.iloc[0:2]

  nombre  edad      ciudad
0   Juan    20    Santiago
1  Maria    25  Valparaiso

In [23]:
df.iloc[:,0]

0     Juan
1    Maria
2    Pedro
3      Ana
Name: nombre, dtype: str

In [ ]:
# iloc — selección por posición entera (como índices de Python), 
# donde el slice es exclusivo en el final. 
# iloc[0:2] devuelve filas 0 y 1.
# Así mismo este criterio para columnas, para este caso se selecciona la columna 0

df.iloc[0:2,0]

0     Juan
1    Maria
Name: nombre, dtype: str

In [ ]:
# Acá se seleccionan las filas 0 y 2 y la columna 0
df.iloc[[0,2],0]

0     Juan
2    Pedro
Name: nombre, dtype: str

In [34]:
df

  nombre  edad       ciudad  anioNacimiento
0   Juan    20     Santiago            2006
1  Maria    25   Valparaiso            2001
2  Pedro    30   Concepcion            1996
3    Ana    35  Antofagasta            1991

Empleando loc (Etiquetas) - Se puede modificar
Se modifica la etiqueta de los indices ()

In [ ]:
# loc — selección por etiquetas/nombres, 
# donde el slice es inclusivo en ambos extremos. 
# loc[0:2] devuelve filas 0, 1 y 2.

df.loc[0:2,'nombre']

0     Juan
1    Maria
2    Pedro
Name: nombre, dtype: str

In [39]:
df.loc[df['edad'] > 24,'nombre']

1    Maria
2    Pedro
3      Ana
Name: nombre, dtype: str

Operaciones

In [ ]:
df2=df[df['edad'] > 24]
df2

  nombre  edad       ciudad
1  Maria    25   Valparaiso
2  Pedro    30   Concepcion
3    Ana    35  Antofagasta

In [30]:
df['anioNacimiento']=2026-df['edad']

In [32]:
df.head()

  nombre  edad       ciudad  anioNacimiento
0   Juan    20     Santiago            2006
1  Maria    25   Valparaiso            2001
2  Pedro    30   Concepcion            1996
3    Ana    35  Antofagasta            1991

Nulos

In [46]:
df_null=pd.DataFrame({'categoria':['A','B','A','B','A','B'],
                      'ventas':[10,None,30,40,None,60],
                      'fecha':['2021-01-01','2021-01-02',None,'2021-01-04','2021-01-05','2021-01-06']})

In [55]:
df_null

  categoria  ventas       fecha
0         A    10.0  2021-01-01
1         B     NaN  2021-01-02
2         A    30.0         NaN
3         B    40.0  2021-01-04
4         A     NaN  2021-01-05
5         B    60.0  2021-01-06

In [47]:
df_null.isnull()

   categoria  ventas  fecha
0      False   False  False
1      False    True  False
2      False   False   True
3      False   False  False
4      False    True  False
5      False   False  False

In [53]:
df_null.isnull().sum()

categoria    0
ventas       2
fecha        1
dtype: int64

In [56]:
df_null

  categoria  ventas       fecha
0         A    10.0  2021-01-01
1         B     NaN  2021-01-02
2         A    30.0         NaN
3         B    40.0  2021-01-04
4         A     NaN  2021-01-05
5         B    60.0  2021-01-06

In [57]:
# Eliminar filas que tengan AL MENOS un nulo
df_null.dropna()

  categoria  ventas       fecha
0         A    10.0  2021-01-01
3         B    40.0  2021-01-04
5         B    60.0  2021-01-06

In [58]:
# Eliminar filas donde TODAS las columnas sean nulas
df_null.dropna(how='all')

  categoria  ventas       fecha
0         A    10.0  2021-01-01
1         B     NaN  2021-01-02
2         A    30.0         NaN
3         B    40.0  2021-01-04
4         A     NaN  2021-01-05
5         B    60.0  2021-01-06

In [59]:
# Eliminar filas con nulos solo en columnas específicas
df_null.dropna(subset=['ventas'])

  categoria  ventas       fecha
0         A    10.0  2021-01-01
2         A    30.0         NaN
3         B    40.0  2021-01-04
5         B    60.0  2021-01-06

In [60]:
# Eliminar COLUMNAS que tengan algún nulo
df_null.dropna(axis=1)

  categoria
0         A
1         B
2         A
3         B
4         A
5         B

In [61]:
df_null
# Llenar todos los nulos con un valor fijo

  categoria  ventas       fecha
0         A    10.0  2021-01-01
1         B     NaN  2021-01-02
2         A    30.0         NaN
3         B    40.0  2021-01-04
4         A     NaN  2021-01-05
5         B    60.0  2021-01-06

In [63]:
# Llenar todos los nulos con un valor fijo
df_null.fillna(0)

  categoria  ventas       fecha
0         A    10.0  2021-01-01
1         B     0.0  2021-01-02
2         A    30.0           0
3         B    40.0  2021-01-04
4         A     0.0  2021-01-05
5         B    60.0  2021-01-06

In [ ]:
# Llenar con la MEDIA de cada columna
df_null.fillna(df_null.mean())

# Tener cuidado con el tipo de dato de la columna
#df_null.dtypes

# Llenar con la MEDIA de cada columna

TypeError: Cannot perform reduction 'mean' with string dtype

In [66]:
df_null['ventas'].fillna(df_null['ventas'].mean())

0    10.0
1    35.0
2    30.0
3    40.0
4    35.0
5    60.0
Name: ventas, dtype: float64

In [ ]:
# Llenar con valores distintos por columna
df_null.fillna({'ventas': df_null['ventas'].mean(), 'fecha': '2026-01-01'})

  categoria  ventas       fecha
0         A    10.0  2021-01-01
1         B    35.0  2021-01-02
2         A    30.0  2026-01-01
3         B    40.0  2021-01-04
4         A    35.0  2021-01-05
5         B    60.0  2021-01-06

Group by

In [42]:
df_group=pd.DataFrame({'categoria':['A','B','A','B','A','B'],
                      'ventas':[10,20,30,40,50,60]})

In [ ]:
df_group.groupby('categoria').sum()

           ventas
categoria
A              90
B             120

In [44]:
df_group.groupby('categoria').mean()

           ventas
categoria
A            30.0
B            40.0

In [45]:
df_group.groupby('categoria').count()

           ventas
categoria
A               3
B               3